//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.BlogMenus = new HashSet<BlogMenu>();
            this.BlogRelatedPosts = new HashSet<BlogRelatedPost>();
            this.BlogThemes = new HashSet<BlogTheme>();
            this.BlogThemeTags = new HashSet<BlogThemeTag>();
        }
    
        public int BlogId { get; set; }
        public string LanguageCode { get; set; }
        public int MainMenuId { get; set; }
        public Nullable<int> ThemeId { get; set; }
        public int AuthoId { get; set; }
        public string Title { get; set; }
        public string Alias { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string Avatar { get; set; }
        public string Background { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string PlanTrip { get; set; }
        public Nullable<int> Comment { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string UserCreate { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> Like { get; set; }
        public Nullable<bool> Hot { get; set; }
        public int Index { get; set; }
        public bool SelectRelatedPost { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual BlogMenuTheme BlogMenuTheme { get; set; }
        public virtual W_Menu W_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogMenu> BlogMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogRelatedPost> BlogRelatedPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogTheme> BlogThemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogThemeTag> BlogThemeTags { get; set; }
    }
}
