//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogMenu
    {
        public int BlogMenuId { get; set; }
        public int BlogId { get; set; }
        public int SubMenu1 { get; set; }
        public int IndexSubMenu1 { get; set; }
        public int SubMenu2 { get; set; }
        public int IndexSubMenu2 { get; set; }
        public int SubMenu3 { get; set; }
        public int IndexSubMenu3 { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
