//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_CruiseTour
    {
        public int CruiseTourId { get; set; }
        public int CruiseId { get; set; }
        public int CruiseTourTypeId { get; set; }
    
        public virtual CR_Cruise CR_Cruise { get; set; }
        public virtual CR_CruiseTourType CR_CruiseTourType { get; set; }
    }
}
