//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_CruiseTourType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_CruiseTourType()
        {
            this.CR_CabinPrice = new HashSet<CR_CabinPrice>();
            this.CR_CabinPriceDetail = new HashSet<CR_CabinPriceDetail>();
            this.CR_CruiseItineraries = new HashSet<CR_CruiseItineraries>();
            this.CR_CruiseTour = new HashSet<CR_CruiseTour>();
        }
    
        public int CruiseTourTypeId { get; set; }
        public string CruiseTourTypeName { get; set; }
        public int Index { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CabinPrice> CR_CabinPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CabinPriceDetail> CR_CabinPriceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CruiseItineraries> CR_CruiseItineraries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CruiseTour> CR_CruiseTour { get; set; }
    }
}
