//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cabin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Cabin()
        {
            this.CR_CabinGallery = new HashSet<CR_CabinGallery>();
            this.CR_CabinPrice = new HashSet<CR_CabinPrice>();
            this.CR_CabinPriceDetail = new HashSet<CR_CabinPriceDetail>();
        }
    
        public int CabinId { get; set; }
        public int CruiseId { get; set; }
        public string CabinName { get; set; }
        public double Acreage { get; set; }
        public string Bed { get; set; }
        public string Balcony { get; set; }
        public int MaxPeople { get; set; }
        public string Description { get; set; }
        public string Conditions { get; set; }
        public string Image { get; set; }
        public string Extrabed { get; set; }
        public string Amenities { get; set; }
        public bool IsDeleted { get; set; }
        public bool Highlight { get; set; }
        public int Index { get; set; }
    
        public virtual CR_Cruise CR_Cruise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CabinGallery> CR_CabinGallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CabinPrice> CR_CabinPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CabinPriceDetail> CR_CabinPriceDetail { get; set; }
    }
}
