//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cruise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Cruise()
        {
            this.CR_Cabin = new HashSet<CR_Cabin>();
            this.CR_CruiseGallery = new HashSet<CR_CruiseGallery>();
            this.CR_CruiseItineraries = new HashSet<CR_CruiseItineraries>();
            this.CR_CruiseMenu = new HashSet<CR_CruiseMenu>();
            this.CR_CruiseTour = new HashSet<CR_CruiseTour>();
        }
    
        public int CruiseId { get; set; }
        public int MainMenuId { get; set; }
        public string CruiseName { get; set; }
        public string CruiseAlias { get; set; }
        public int NumberCabin { get; set; }
        public double Excellent { get; set; }
        public string Image { get; set; }
        public string Destination { get; set; }
        public string PromotionTitle { get; set; }
        public string PromotionContent { get; set; }
        public string Activate { get; set; }
        public int Star { get; set; }
        public Nullable<bool> Highlight { get; set; }
        public string Overview { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public string Note { get; set; }
        public Nullable<int> Index { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool IsDeleted { get; set; }
        public string Meals { get; set; }
        public string Transportation { get; set; }
        public string Accommodation { get; set; }
        public string PriceIncludes { get; set; }
        public string PriceExcludes { get; set; }
        public string Cancellation { get; set; }
        public string CancellationBadWeather { get; set; }
        public string Policy { get; set; }
        public string Facilities { get; set; }
        public bool BestCruise { get; set; }
        public bool BestSeller { get; set; }
        public bool TopCruise { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cabin> CR_Cabin { get; set; }
        public virtual W_Menu W_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CruiseGallery> CR_CruiseGallery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CruiseItineraries> CR_CruiseItineraries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CruiseMenu> CR_CruiseMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CruiseTour> CR_CruiseTour { get; set; }
    }
}
