//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_CabinPrice
    {
        public int CabinPriceId { get; set; }
        public int CabinId { get; set; }
        public int CruiseTourTypeId { get; set; }
        public decimal DiscountOverMaxNumber { get; set; }
    
        public virtual CR_Cabin CR_Cabin { get; set; }
        public virtual CR_CruiseTourType CR_CruiseTourType { get; set; }
    }
}
