//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_CruiseBookTour
    {
        public int Id { get; set; }
        public string Gender { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public int PhoneNumber { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
        public string SocialMedia { get; set; }
        public string SpecialRequests { get; set; }
        public System.DateTime Departure { get; set; }
        public string Cruise { get; set; }
        public string Cabin { get; set; }
        public string People { get; set; }
        public string TourType { get; set; }
        public string ServiceHotel { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    }
}
