//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class D_GuideStep
    {
        public int GuideStepId { get; set; }
        public int GuideId { get; set; }
        public int Index { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
    
        public virtual D_Guide D_Guide { get; set; }
    }
}
