//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB : DbContext
    {
        public DB()
            : base("name=DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CR_Cabin> CR_Cabin { get; set; }
        public virtual DbSet<CR_CabinGallery> CR_CabinGallery { get; set; }
        public virtual DbSet<CR_CabinPrice> CR_CabinPrice { get; set; }
        public virtual DbSet<CR_CabinPriceDetail> CR_CabinPriceDetail { get; set; }
        public virtual DbSet<CR_Cruise> CR_Cruise { get; set; }
        public virtual DbSet<CR_CruiseBookTour> CR_CruiseBookTour { get; set; }
        public virtual DbSet<CR_CruiseGallery> CR_CruiseGallery { get; set; }
        public virtual DbSet<CR_CruiseItineraries> CR_CruiseItineraries { get; set; }
        public virtual DbSet<CR_CruiseMenu> CR_CruiseMenu { get; set; }
        public virtual DbSet<CR_CruiseTour> CR_CruiseTour { get; set; }
        public virtual DbSet<CR_CruiseTourType> CR_CruiseTourType { get; set; }
        public virtual DbSet<D_Application> D_Application { get; set; }
        public virtual DbSet<D_Guide> D_Guide { get; set; }
        public virtual DbSet<D_GuideStep> D_GuideStep { get; set; }
        public virtual DbSet<D_Path> D_Path { get; set; }
        public virtual DbSet<D_Role> D_Role { get; set; }
        public virtual DbSet<D_RolePath> D_RolePath { get; set; }
        public virtual DbSet<D_Screen> D_Screen { get; set; }
        public virtual DbSet<D_User> D_User { get; set; }
        public virtual DbSet<D_UserHistory> D_UserHistory { get; set; }
        public virtual DbSet<D_UserMembership> D_UserMembership { get; set; }
        public virtual DbSet<D_UserPath> D_UserPath { get; set; }
        public virtual DbSet<D_UserProfile> D_UserProfile { get; set; }
        public virtual DbSet<D_UserRole> D_UserRole { get; set; }
        public virtual DbSet<D_UserScreen> D_UserScreen { get; set; }
        public virtual DbSet<H_RoomType> H_RoomType { get; set; }
        public virtual DbSet<H_RoomTypeGallery> H_RoomTypeGallery { get; set; }
        public virtual DbSet<QA_Question> QA_Question { get; set; }
        public virtual DbSet<QA_QuestionMenu> QA_QuestionMenu { get; set; }
        public virtual DbSet<QA_QuestionTour> QA_QuestionTour { get; set; }
        public virtual DbSet<Require> Requires { get; set; }
        public virtual DbSet<RV_Review> RV_Review { get; set; }
        public virtual DbSet<RV_ReviewMenu> RV_ReviewMenu { get; set; }
        public virtual DbSet<RV_ReviewTour> RV_ReviewTour { get; set; }
        public virtual DbSet<RV_TravelerRating> RV_TravelerRating { get; set; }
        public virtual DbSet<RV_TravelerType> RV_TravelerType { get; set; }
        public virtual DbSet<S_Service> S_Service { get; set; }
        public virtual DbSet<S_ServiceGallery> S_ServiceGallery { get; set; }
        public virtual DbSet<S_ServiceMenu> S_ServiceMenu { get; set; }
        public virtual DbSet<SR_Destination> SR_Destination { get; set; }
        public virtual DbSet<SR_DestinationSearchTourType> SR_DestinationSearchTourType { get; set; }
        public virtual DbSet<SR_SearchTourType> SR_SearchTourType { get; set; }
        public virtual DbSet<SR_Theme> SR_Theme { get; set; }
        public virtual DbSet<SR_ThemeMenu> SR_ThemeMenu { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<T2_Customize> T2_Customize { get; set; }
        public virtual DbSet<T2_Tour> T2_Tour { get; set; }
        public virtual DbSet<T2_TourBook> T2_TourBook { get; set; }
        public virtual DbSet<T2_TourGallery> T2_TourGallery { get; set; }
        public virtual DbSet<T2_TourJourney> T2_TourJourney { get; set; }
        public virtual DbSet<T2_TourMenu> T2_TourMenu { get; set; }
        public virtual DbSet<T2_TourRoomType> T2_TourRoomType { get; set; }
        public virtual DbSet<T2_TourRoomTypePrice> T2_TourRoomTypePrice { get; set; }
        public virtual DbSet<T2_TourRoomTypePriceGroup> T2_TourRoomTypePriceGroup { get; set; }
        public virtual DbSet<T2_TourShortJourney> T2_TourShortJourney { get; set; }
        public virtual DbSet<T2_TourTypeGroup> T2_TourTypeGroup { get; set; }
        public virtual DbSet<W_ArticalMenu> W_ArticalMenu { get; set; }
        public virtual DbSet<W_Article> W_Article { get; set; }
        public virtual DbSet<W_ArticleHistory> W_ArticleHistory { get; set; }
        public virtual DbSet<W_ArticleRelatedPost> W_ArticleRelatedPost { get; set; }
        public virtual DbSet<W_Company> W_Company { get; set; }
        public virtual DbSet<W_Contact> W_Contact { get; set; }
        public virtual DbSet<W_CoreValue> W_CoreValue { get; set; }
        public virtual DbSet<W_EmailConfig> W_EmailConfig { get; set; }
        public virtual DbSet<W_EmailRegister> W_EmailRegister { get; set; }
        public virtual DbSet<W_Employee> W_Employee { get; set; }
        public virtual DbSet<W_Gallery> W_Gallery { get; set; }
        public virtual DbSet<W_GalleryTab> W_GalleryTab { get; set; }
        public virtual DbSet<W_Hotel> W_Hotel { get; set; }
        public virtual DbSet<W_HotelGallery> W_HotelGallery { get; set; }
        public virtual DbSet<W_HotelMenu> W_HotelMenu { get; set; }
        public virtual DbSet<W_Language> W_Language { get; set; }
        public virtual DbSet<W_Menu> W_Menu { get; set; }
        public virtual DbSet<W_MenuType> W_MenuType { get; set; }
        public virtual DbSet<W_Partner> W_Partner { get; set; }
        public virtual DbSet<W_Plugin> W_Plugin { get; set; }
        public virtual DbSet<W_Slider> W_Slider { get; set; }
        public virtual DbSet<W_SliderMenu> W_SliderMenu { get; set; }
        public virtual DbSet<W_SliderTab> W_SliderTab { get; set; }
        public virtual DbSet<W_TemplateEmail> W_TemplateEmail { get; set; }
        public virtual DbSet<W_TermCondition> W_TermCondition { get; set; }
        public virtual DbSet<W_ThemesMenu> W_ThemesMenu { get; set; }
        public virtual DbSet<W_TypeEmail> W_TypeEmail { get; set; }
        public virtual DbSet<W_TypeTermCondition> W_TypeTermCondition { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<BlogMenu> BlogMenus { get; set; }
        public virtual DbSet<BlogMenuTheme> BlogMenuThemes { get; set; }
        public virtual DbSet<BlogRelatedPost> BlogRelatedPosts { get; set; }
        public virtual DbSet<BlogTag> BlogTags { get; set; }
        public virtual DbSet<BlogTheme> BlogThemes { get; set; }
        public virtual DbSet<BlogThemeTag> BlogThemeTags { get; set; }
        public virtual DbSet<Guide> Guides { get; set; }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
