//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_RoomType
    {
        public int RoomTypeId { get; set; }
        public int HotelId { get; set; }
        public string RoomTypeName { get; set; }
        public string Image { get; set; }
        public int MaxPeople { get; set; }
        public double Price { get; set; }
        public Nullable<double> PromotionalPrice { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public string MoreInformation { get; set; }
    }
}
