//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA_Question
    {
        public int QuestionId { get; set; }
        public string LanguageCode { get; set; }
        public string FullName { get; set; }
        public int MainMenuId { get; set; }
        public string Title { get; set; }
        public string Alias { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string Avatar { get; set; }
        public string Icon { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<int> View { get; set; }
        public Nullable<int> Comment { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string UserCreate { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> Destination { get; set; }
        public Nullable<bool> Travel { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<bool> SelectRelatedPost { get; set; }
    }
}
