//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Require
    {
        public int RequireId { get; set; }
        public string LanguageCode { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string City { get; set; }
        public string Year { get; set; }
        public string Address { get; set; }
        public string DateArrival { get; set; }
        public string DateDeparture { get; set; }
        public string People { get; set; }
        public string Time { get; set; }
        public string Destination { get; set; }
        public string RoomType { get; set; }
        public string TypeTravel { get; set; }
        public string RoomSelect { get; set; }
        public string Meal { get; set; }
        public string Budjet { get; set; }
        public string PhoneNumber { get; set; }
        public string Tickets { get; set; }
    }
}
