//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_Review
    {
        public int ReviewId { get; set; }
        public string LanguageCode { get; set; }
        public string Image { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public string ReviewFor { get; set; }
        public Nullable<int> Index { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
