//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_ServiceMenu
    {
        public int ServiceMenuId { get; set; }
        public int ServiceId { get; set; }
        public int MenuId { get; set; }
        public int Index { get; set; }
    }
}
