//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SR_Destination
    {
        public int DestinationId { get; set; }
        public string DestinationType { get; set; }
        public string DestinationName { get; set; }
        public string ParentName { get; set; }
        public string Color { get; set; }
    }
}
