//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T2_TourRoomTypePriceGroup
    {
        public int TourRoomTypePriceGroupId { get; set; }
        public int TourRoomTypePriceId { get; set; }
        public int TourTypeGroupId { get; set; }
        public double Price { get; set; }
        public double PromotionalPrice { get; set; }
        public double PriceChild { get; set; }
        public double PriceInfant { get; set; }
    
        public virtual T2_TourRoomTypePrice T2_TourRoomTypePrice { get; set; }
        public virtual T2_TourTypeGroup T2_TourTypeGroup { get; set; }
    }
}
