//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T2_TourBook
    {
        public int BookTourID { get; set; }
        public string LanguageCode { get; set; }
        public string People { get; set; }
        public string TourType { get; set; }
        public string DateArrival { get; set; }
        public string Budget { get; set; }
        public string Message { get; set; }
        public string Gender { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string Address { get; set; }
        public int Phone { get; set; }
        public string communicate { get; set; }
        public string Nationality { get; set; }
        public int Year { get; set; }
        public string City { get; set; }
    }
}
