//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class T2_TourTypeGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T2_TourTypeGroup()
        {
            this.T2_TourRoomTypePriceGroup = new HashSet<T2_TourRoomTypePriceGroup>();
        }
    
        public int TourTypeGroupId { get; set; }
        public string TourTypeGroupName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T2_TourRoomTypePriceGroup> T2_TourRoomTypePriceGroup { get; set; }
    }
}
