//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public W_Article()
        {
            this.W_ArticalMenu = new HashSet<W_ArticalMenu>();
            this.W_ArticleHistory = new HashSet<W_ArticleHistory>();
            this.W_ArticleRelatedPost = new HashSet<W_ArticleRelatedPost>();
            this.W_ThemesMenu = new HashSet<W_ThemesMenu>();
        }
    
        public int ArticleId { get; set; }
        public string LanguageCode { get; set; }
        public int MainMenuId { get; set; }
        public string Title { get; set; }
        public string Alias { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string Avatar { get; set; }
        public string Icon { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<int> View { get; set; }
        public Nullable<int> Comment { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string UserCreate { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> Destination { get; set; }
        public Nullable<bool> Travel { get; set; }
        public int Index { get; set; }
        public bool SelectRelatedPost { get; set; }
        public Nullable<bool> Hot { get; set; }
    
        public virtual D_User D_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_ArticalMenu> W_ArticalMenu { get; set; }
        public virtual W_Menu W_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_ArticleHistory> W_ArticleHistory { get; set; }
        public virtual W_Language W_Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_ArticleRelatedPost> W_ArticleRelatedPost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_ThemesMenu> W_ThemesMenu { get; set; }
    }
}
