//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_Company
    {
        public int CompanyId { get; set; }
        public string LanguageCode { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string Logo { get; set; }
        public string Image { get; set; }
        public string Favicon { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string LocationMap { get; set; }
        public string IframeMap { get; set; }
        public string Website { get; set; }
        public string Tripadvisor { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Twitter { get; set; }
        public string Youtube { get; set; }
        public string CopyRight { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
    
        public virtual W_Language W_Language { get; set; }
    }
}
