//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_Gallery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public W_Gallery()
        {
            this.W_GalleryTab = new HashSet<W_GalleryTab>();
        }
    
        public int GalleryId { get; set; }
        public string LanguageCode { get; set; }
        public int MenuId { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public int Index { get; set; }
        public string Description { get; set; }
    
        public virtual W_Menu W_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_GalleryTab> W_GalleryTab { get; set; }
    }
}
