//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_SliderMenu
    {
        public int SliderMenuId { get; set; }
        public int SliderId { get; set; }
        public int MenuId { get; set; }
        public int Index { get; set; }
    
        public virtual W_Slider W_Slider { get; set; }
    }
}
