//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_TemplateEmail
    {
        public int TemplateEmailId { get; set; }
        public string LanguageCode { get; set; }
        public int TypeEmailId { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
    
        public virtual W_Language W_Language { get; set; }
        public virtual W_TypeEmail W_TypeEmail { get; set; }
    }
}
