//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_TermCondition
    {
        public int TermConditionId { get; set; }
        public string LanguageCode { get; set; }
        public int TypeTermConditionId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
    
        public virtual W_Language W_Language { get; set; }
        public virtual W_TypeTermCondition W_TypeTermCondition { get; set; }
    }
}
