//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsiaCharmtours.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_ThemesMenu
    {
        public int ThemesId { get; set; }
        public int MenuId { get; set; }
        public int ArticleId { get; set; }
    
        public virtual W_Article W_Article { get; set; }
        public virtual W_Menu W_Menu { get; set; }
    }
}
